### ISSUE TITLE
No rule to make target error

### ISSUE THREAD

**Issue by Thwar** [webb/niem-ndr-tools#6]
I am following the instructions word by word, and I am stuck in this part, what does it mean?

![untitled](https://cloud.githubusercontent.com/assets/11199179/8958211/75a50aba-35d1-11e5-8a2c-82bcf20906fd.png)

**Comment by webb** [comment]
The instructions are definitely out of date. I edited them a bit. You're most likely best off pulling down a pre-built zip from https://github.com/webb/niem-ndr-tools/releases. Add the bin directory to your path.

**Comment by webb** [comment]
BTW, just submit a new issue if this wasn't enough detail for you!
